[package]
name = "termifind"
version = "0.1.0"
authors = ["Joseph T Lyons <JosephTLyons@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.9.2"
term_size = "0.3.1"
